### ISSUE TITLE
Comparison to the other whiteboard app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/integration_whiteboard#7]
Hey, 

I wonder what are the advantages in comparison to the other available whiteboard app https://apps.nextcloud.com/apps/whiteboard and why you decided to create a new one?

Thanks for the feedback!

**Comment by socialize-IT** [comment]
Guess there are lot of advantages, e.g. sharing with anonymous users per link, moving painted elements, adding zones, presentation mode, ... It#s a bit like the "old" whiteboard app is like microsoft paint, while the spacedeck one is a real online whiteboard.

**Comment by szaimen** [comment]
Thanks for the answer!
